// Mocks generated by Mockito 5.4.6 from annotations
// in virelo_core/test/crypto/offline_crypto_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cryptography/cryptography.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:virelo_core/offline_sync/offline_storage_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OfflineStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineStorageService extends _i1.Mock
    implements _i2.OfflineStorageService {
  @override
  _i3.Future<int> getCurrentSequenceNumber() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentSequenceNumber,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> incrementAndGetSequenceNumber() => (super.noSuchMethod(
        Invocation.method(
          #incrementAndGetSequenceNumber,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> saveKeyPair(_i4.SimpleKeyPair? keyPair) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveKeyPair,
          [keyPair],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i4.SimpleKeyPair?> getKeyPair(_i4.Ed25519? algorithm) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKeyPair,
          [algorithm],
        ),
        returnValue: _i3.Future<_i4.SimpleKeyPair?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.SimpleKeyPair?>.value(),
      ) as _i3.Future<_i4.SimpleKeyPair?>);

  @override
  _i3.Future<String?> getPublicKeyBase64() => (super.noSuchMethod(
        Invocation.method(
          #getPublicKeyBase64,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
        returnValueForMissingStub: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> saveOfflineBudget(double? amount) => (super.noSuchMethod(
        Invocation.method(
          #saveOfflineBudget,
          [amount],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<double> getOfflineBudget() => (super.noSuchMethod(
        Invocation.method(
          #getOfflineBudget,
          [],
        ),
        returnValue: _i3.Future<double>.value(0.0),
        returnValueForMissingStub: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<void> deductOfflineBudget(double? amount) => (super.noSuchMethod(
        Invocation.method(
          #deductOfflineBudget,
          [amount],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveOfflineTransaction(Map<String, dynamic>? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveOfflineTransaction,
          [transaction],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getOfflineTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getOfflineTransactions,
          [],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
        returnValueForMissingStub: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<void> removeOfflineTransaction(String? uuid) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeOfflineTransaction,
          [uuid],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearOfflineTransactions() => (super.noSuchMethod(
        Invocation.method(
          #clearOfflineTransactions,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
